<div x-data="riwayatPemilikPage()" x-init="init()" class="owner-page">
  <div class="owner-page-header"><div><a href="<?= BASE_URL ?>/pemilik" @click.prevent="utils.goBack($el.href)" class="owner-back-link"><?= masterIconSvg('arrow-left', 'h-4 w-4') ?> Kembali</a><p class="owner-eyebrow mt-3">Arsip Operasional</p><h2 class="owner-title">Riwayat</h2><p class="owner-subtitle">Data yang sudah selesai dipisahkan dari pekerjaan aktif.</p></div></div>

  <nav data-help="help-history-tabs" class="owner-segmented" aria-label="Jenis riwayat">
    <button type="button" @click="setTab('penghuni')" :class="tab==='penghuni'?'is-active':''"><?= masterIconSvg('users-round','h-4 w-4') ?> Riwayat Penghuni</button>
    <button type="button" @click="setTab('keuangan')" :class="tab==='keuangan'?'is-active':''"><?= masterIconSvg('wallet','h-4 w-4') ?> Riwayat Keuangan</button>
  </nav>

  <div x-show="tab==='keuangan' && idPenghuni" x-cloak class="owner-context-panel"><div class="owner-context-header"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-violet-50 text-violet-600"><?= masterIconSvg('user-round','h-5 w-5') ?></span><div class="min-w-0 flex-1"><p class="text-xs font-semibold uppercase tracking-wider text-violet-600">Riwayat keuangan penghuni</p><h3 class="mt-1 truncate font-bold text-slate-900" x-text="selectedOccupantName || 'Memuat penghuni...'"></h3><p class="mt-1 text-xs text-slate-500">Seluruh tagihan dan pembayaran yang terhubung dengan penghuni ini.</p></div><button type="button" @click="clearOccupant()" class="owner-action-secondary shrink-0">Lihat Semua</button></div></div>

  <div class="card grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
    <div class="sm:col-span-2 xl:col-span-1"><label class="label" for="history-search">Cari riwayat</label><input id="history-search" type="search" x-model="search" @input.debounce.350ms="load()" class="input" :placeholder="tab==='penghuni'?'Nama, NIK, atau nomor HP':'Penghuni atau nomor tagihan'"></div>
    <div><label class="label" for="history-kos">Properti</label><select id="history-kos" x-model="idKos" @change="changeKos()" class="select"><option value="">Semua properti</option><template x-for="kos in kosList" :key="kos.id_kos"><option :value="String(kos.id_kos)" x-text="kos.nama_kos"></option></template></select></div>
    <div><label class="label" for="history-type">Tipe kamar</label><select id="history-type" x-model="idTipeKamar" @change="changeType()" class="select" :disabled="!idKos"><option value="" x-text="idKos ? 'Semua tipe kamar' : 'Pilih properti dahulu'"></option><template x-for="type in typeList" :key="type.id_tipe_kamar"><option :value="String(type.id_tipe_kamar)" x-text="type.nama_tipe"></option></template></select></div>
    <div><label class="label" for="history-room">Nomor kamar</label><select id="history-room" x-model="idKamar" @change="load()" class="select" :disabled="!idTipeKamar"><option value="" x-text="idTipeKamar ? 'Semua nomor kamar' : 'Pilih tipe kamar dahulu'"></option><template x-for="room in roomList" :key="room.id_kamar"><option :value="String(room.id_kamar)" x-text="'Kamar ' + room.nomor_kamar"></option></template></select></div>
  </div>

  <div x-show="loading" class="card py-12 text-center text-sm text-slate-500">Memuat riwayat...</div>
  <div x-show="!loading&&!items.length" x-cloak class="owner-empty"><div class="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100 text-slate-500"><?= masterIconSvg('history','h-6 w-6') ?></div><h3 class="font-semibold text-slate-900">Belum ada riwayat</h3><p class="mt-1 text-sm text-slate-500">Data yang sesuai dengan pilihan Anda belum tersedia.</p></div>

  <div data-help="help-history-list" x-show="!loading&&items.length" x-cloak class="grid min-w-0 gap-3 lg:grid-cols-2">
    <template x-for="item in items" :key="tab==='penghuni'?item.id_penghuni:item.id_tagihan">
      <article class="owner-panel min-w-0" :class="tab==='penghuni'?'cursor-pointer transition hover:-translate-y-0.5 hover:border-violet-200 hover:shadow-md':''" @click="tab==='penghuni' && openOccupantHistory(item)" @keydown.enter.prevent="tab==='penghuni' && openOccupantHistory(item)" :role="tab==='penghuni'?'button':null" :tabindex="tab==='penghuni'?0:null">
        <template x-if="tab==='penghuni'"><div class="min-w-0"><div class="flex min-w-0 items-start justify-between gap-3"><div class="min-w-0"><h3 class="owner-copy-full font-bold text-slate-900" x-text="item.nama"></h3><p class="owner-copy-full mt-1 text-xs text-slate-500" x-text="item.nama_kos+' · Kamar '+item.nomor_kamar+' · '+item.tipe_kamar"></p></div><span class="shrink-0 rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">Sudah keluar</span></div><div class="mt-3 grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-3 text-xs"><div><span class="text-slate-400">Masuk</span><strong class="mt-1 block" x-text="date(item.tanggal_masuk)"></strong></div><div><span class="text-slate-400">Keluar</span><strong class="mt-1 block" x-text="date(item.tanggal_keluar)"></strong></div></div><div class="mt-3 flex items-center justify-between text-xs font-semibold text-violet-700"><span>Lihat tagihan &amp; pembayaran</span><?= masterIconSvg('chevron-right','h-4 w-4') ?></div></div></template>
        <template x-if="tab==='keuangan'"><div class="min-w-0"><div class="flex min-w-0 items-start justify-between gap-3"><div class="min-w-0"><h3 class="owner-copy-full font-bold text-slate-900" x-text="'Kamar '+item.nomor_kamar+' · '+(item.nama_penghuni||'-')"></h3><p class="owner-copy-full mt-1 text-xs text-slate-500" x-text="item.nama_kos+' · '+item.tipe_kamar"></p></div><span class="shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold" :class="historyStatusClass(item.status)" x-text="historyStatusLabel(item.status)"></span></div><div class="mt-3 rounded-xl border border-blue-100 bg-blue-50/70 p-3"><p class="text-[11px] font-semibold uppercase tracking-wider text-blue-500">Periode tagihan</p><div class="mt-1 flex flex-wrap items-center gap-1.5 font-bold text-slate-800"><span x-text="date(item.tanggal_mulai)"></span><span class="text-slate-400">–</span><span x-text="date(item.tanggal_selesai)"></span></div></div><div class="mt-2 flex items-end justify-between gap-3 rounded-xl bg-slate-50 p-3"><div class="min-w-0"><p class="text-[11px] text-slate-400">Total tagihan</p><strong class="owner-copy-full mt-1 block text-lg" x-text="rupiah(item.total_tagihan)"></strong></div><a :href="BASE_URL+'/pemilik/riwayat/tagihan?id_tagihan='+item.id_tagihan" class="owner-action-secondary shrink-0">Detail</a></div></div></template>
      </article>
    </template>
  </div>
</div>
<script>
function riwayatPemilikPage(){return{
tab:utils.getQuery('tab')==='keuangan'?'keuangan':'penghuni',search:'',idKos:'',idTipeKamar:'',idKamar:'',idPenghuni:utils.getQuery('id_penghuni')||'',selectedOccupantName:'',kosList:[],typeList:[],roomList:[],items:[],loading:false,
async init(){try{const requests=[API.get('/pemilik/kamar/kos',false)];if(this.idPenghuni)requests.push(API.get('/pemilik/penghuni/show?id_penghuni='+encodeURIComponent(this.idPenghuni),false));const result=await Promise.all(requests);this.kosList=result[0].data||[];if(result[1])this.selectedOccupantName=result[1].data?.nama||''}catch(e){this.kosList=[]}await this.load()},
setTab(v){this.tab=v;if(v==='penghuni'){this.idPenghuni='';this.selectedOccupantName=''}this.syncUrl();this.load()},
syncUrl(){const p=new URLSearchParams();if(this.tab==='keuangan')p.set('tab','keuangan');if(this.idPenghuni)p.set('id_penghuni',this.idPenghuni);history.replaceState({},'',location.pathname+(p.toString()?'?'+p:''))},
openOccupantHistory(item){this.tab='keuangan';this.idPenghuni=String(item.id_penghuni);this.selectedOccupantName=item.nama||'';this.search='';this.idKos='';this.idTipeKamar='';this.idKamar='';this.typeList=[];this.roomList=[];this.syncUrl();this.load();window.scrollTo({top:0,behavior:'smooth'})},
clearOccupant(){this.idPenghuni='';this.selectedOccupantName='';this.syncUrl();this.load()},
async changeKos(){this.idTipeKamar='';this.idKamar='';this.roomList=[];this.typeList=[];if(this.idKos){try{const r=await API.get('/pemilik/tipe-kamar?id_kos='+encodeURIComponent(this.idKos),false);this.typeList=r.data||[]}catch(e){this.typeList=[]}}await this.load()},
async changeType(){this.idKamar='';this.roomList=[];if(this.idTipeKamar){try{const p=new URLSearchParams({id_kos:this.idKos,id_tipe_kamar:this.idTipeKamar});const r=await API.get('/pemilik/kamar?'+p.toString(),false);this.roomList=r.data||[]}catch(e){this.roomList=[]}}await this.load()},
async load(){this.loading=true;try{const p=new URLSearchParams();if(!(this.tab==='keuangan'&&this.idPenghuni))p.set('scope','riwayat');if(this.search.trim())p.set('search',this.search.trim());if(this.idKos)p.set('id_kos',this.idKos);if(this.idTipeKamar)p.set('id_tipe_kamar',this.idTipeKamar);if(this.idKamar)p.set('id_kamar',this.idKamar);if(this.tab==='keuangan'&&this.idPenghuni)p.set('id_penghuni',this.idPenghuni);const endpoint=this.tab==='penghuni'?'/pemilik/penghuni':'/pemilik/tagihan';const r=await API.get(endpoint+'?'+p.toString(),false);this.items=r.data||[]}catch(e){console.error(e);this.items=[]}finally{this.loading=false}},
historyStatusLabel(v){return({belum_lunas:'Belum lunas',sebagian:'Sebagian',lunas:'Lunas',dibatalkan:'Dibatalkan'})[v]||v},historyStatusClass(v){return({belum_lunas:'bg-rose-50 text-rose-700',sebagian:'bg-amber-50 text-amber-700',lunas:'bg-emerald-50 text-emerald-700',dibatalkan:'bg-slate-100 text-slate-600'})[v]||'bg-slate-100 text-slate-600'},date(v){return v?new Date(v+'T00:00:00').toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}):'-'},rupiah(v){return utils.formatRupiah(v)}
}}
</script>
