<div x-data="pemilikLanggananCheckout()" x-init="init()" class="owner-page max-w-4xl">
  <div class="owner-form-heading"><a :href="window.BASE_URL + '/pemilik/langganan'" @click.prevent="utils.goBack($el.href)" class="owner-back-link"><?= masterIconSvg('arrow-left', 'h-4 w-4') ?> Kembali</a><p class="owner-eyebrow mt-3">Konfirmasi</p><h2 class="owner-title">Checkout BetaKos Pro</h2><p class="owner-subtitle">Periksa pesanan, lalu pilih metode pembayaran.</p></div>
  <div x-show="loading" class="card h-48 animate-pulse"></div>
  <div x-show="!loading&&pendingPayment" x-cloak class="rounded-2xl border border-amber-200 bg-amber-50 p-4"><h3 class="font-bold text-amber-900">Pembayaran masih diproses</h3><p class="mt-1 text-sm text-amber-700">Selesaikan atau tunggu pemeriksaan order sebelumnya.</p><a :href="window.BASE_URL + '/pemilik/langganan/pembayaran'" class="btn-subscription mt-4">Lihat pembayaran</a></div>
  <template x-if="!loading&&!pendingPayment&&selectedPackage"><div class="subscription-checkout-grid">
    <section class="space-y-4">
      <div class="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5">
        <div class="flex items-start justify-between gap-4"><div><p class="text-xs font-semibold text-slate-500">Paket dipilih</p><h3 class="mt-1 text-lg font-bold text-slate-900" x-text="durationLabel(selectedPackage.durasi_bulan)+' BetaKos Pro'"></h3></div><a :href="window.BASE_URL + '/pemilik/langganan?paket='+encodeURIComponent(selectedPackage.kode)" class="text-xs font-bold text-emerald-700">Ubah paket</a></div>
        <dl class="mt-4 space-y-3 border-t border-slate-100 pt-4 text-sm"><div class="flex justify-between gap-4"><dt class="text-slate-500" x-text="formatRupiah(selectedPackage.harga_bulanan)+' × '+selectedPackage.durasi_bulan+' bulan'"></dt><dd class="font-semibold" x-text="formatRupiah(selectedPackage.pricing?.harga_normal)"></dd></div><div x-show="selectedPackage.pricing?.diskon_promo" class="flex justify-between gap-4 text-emerald-700"><dt>Promo 6 bulan pertama</dt><dd class="font-semibold" x-text="'−'+formatRupiah(selectedPackage.pricing?.diskon_promo)"></dd></div><div class="flex justify-between gap-4 border-t border-slate-100 pt-3"><dt class="font-bold text-slate-900">Total</dt><dd class="text-lg font-extrabold text-slate-900" x-text="formatRupiah(displayPrice)"></dd></div></dl>
      </div>
      <div x-show="!isFree" class="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><h3 class="font-bold text-slate-900">Metode pembayaran</h3><p class="mt-1 text-xs text-slate-500">QRIS otomatis, sedangkan transfer manual diperiksa admin.</p><div class="mt-4 grid gap-2 sm:grid-cols-2"><template x-for="m in paymentMethods" :key="m.jenis==='qris'?'qris':m.id_metode_pembayaran"><button type="button" @click="selectedMethod=m.jenis==='qris'?'qris':Number(m.id_metode_pembayaran)" class="rounded-xl border p-3 text-left" :class="selectedMethod===(m.jenis==='qris'?'qris':Number(m.id_metode_pembayaran))?'border-emerald-500 bg-emerald-50':'border-slate-200'"><div class="flex items-center justify-between gap-2"><span class="text-sm font-bold text-slate-900" x-text="m.jenis==='qris'?'QRIS':m.nama_provider"></span><span class="h-4 w-4 rounded-full border" :class="selectedMethod===(m.jenis==='qris'?'qris':Number(m.id_metode_pembayaran))?'border-4 border-emerald-600':'border-slate-300'"></span></div><p class="mt-1 text-xs text-slate-500" x-text="m.jenis==='qris'?'Terverifikasi otomatis':m.nomor_tujuan+' · '+m.nama_penerima"></p></button></template></div></div>
    </section>
    <aside class="h-fit rounded-2xl border border-slate-200 bg-white p-4 lg:sticky lg:top-20"><p class="text-xs text-slate-500">Total pembayaran</p><p class="mt-1 text-2xl font-extrabold text-slate-900" x-text="formatRupiah(displayPrice)"></p><form class="mt-4 space-y-4" @submit.prevent="submit()"><div x-show="!isFree&&selectedMethod!=='qris'"><label class="text-sm font-semibold text-slate-700">Bukti pembayaran</label><input x-ref="proof" type="file" accept="image/jpeg,image/png,image/webp" class="input mt-2 w-full"><p class="mt-1 text-xs text-slate-500">Maksimal 5 MB.</p></div><p class="rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-600" x-text="isFree?'Tidak diperlukan pembayaran. Pro langsung aktif.':selectedMethod==='qris'?'QR dibuat setelah Anda melanjutkan.':'Bukti akan diperiksa admin.'"></p><button type="submit" class="btn-subscription w-full" :disabled="submitting||(!isFree&&!selectedMethod)" x-text="submitting?'Memproses...':isFree?'Aktifkan gratis':'Bayar '+formatRupiah(displayPrice)"></button></form></aside>
  </div></template>
</div>
<script>
function pemilikLanggananCheckout(){return{loading:true,submitting:false,packageCode:<?= json_encode_safe((string)query('paket','pro_1_tahun')) ?>,packages:[],selectedPackage:null,pendingPayment:null,paymentMethods:[],selectedMethod:'qris',get displayPrice(){return Number(this.selectedPackage?.pricing?.harga_final||0)},get isFree(){return this.displayPrice===0},async init(){try{const r=await API.get('/pemilik/langganan/checkout',false);this.packages=r.data.paket||[];this.pendingPayment=r.data.pending_payment||null;this.paymentMethods=r.data.payment_methods||[];this.selectedPackage=this.packages.find(i=>i.kode===this.packageCode)||this.packages[0]||null;if(this.selectedPackage)this.packageCode=this.selectedPackage.kode}finally{this.loading=false}},durationLabel(m){return Number(m)===12?'1 Tahun':Number(m)===24?'2 Tahun':'6 Bulan'},formatRupiah(v){return Alpine.store('utils').formatRupiah(v)},async submit(){if(!this.selectedPackage||(!this.isFree&&!this.selectedMethod))return;const f=new FormData();f.append('kode_paket',this.selectedPackage.kode);if(!this.isFree){f.append('metode_pembayaran',this.selectedMethod==='qris'?'qris':String(this.selectedMethod));if(this.selectedMethod!=='qris'){const file=this.$refs.proof?.files?.[0];if(!file){Alpine.store('ui').toast('Bukti pembayaran wajib diunggah.','error');return}f.append('bukti_pembayaran',file)}}this.submitting=true;try{const r=await API.post('/pemilik/langganan/pembayaran',f);const id=r.data?.id_pembayaran_langganan;location.href=this.isFree?window.BASE_URL+'/pemilik/langganan':window.BASE_URL+'/pemilik/langganan/pembayaran'+(id?'?id='+encodeURIComponent(id):'')}finally{this.submitting=false}}}}
</script>
