<div x-data="pemilikLanggananPage()" x-init="init()" class="owner-page max-w-5xl">
  <div class="owner-page-header">
    <div><p class="owner-eyebrow">Paket Akun</p><h2 class="owner-title">BetaKos Pro</h2><p class="owner-subtitle">Pilih durasi yang sesuai. Semua paket membuka fitur Pro yang sama.</p></div>
    <a :href="window.BASE_URL + '/pemilik/langganan/riwayat'" class="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-emerald-700"><?= masterIconSvg('history', 'h-4 w-4') ?> Riwayat</a>
  </div>
  <div x-show="upgradeRequested" x-cloak class="mb-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Fitur yang Anda pilih membutuhkan BetaKos Pro. Data Anda tetap aman.</div>
  <div x-show="loading" class="grid gap-3 sm:grid-cols-3"><div class="card h-36 animate-pulse"></div><div class="card h-36 animate-pulse"></div><div class="card h-36 animate-pulse"></div></div>
  <template x-if="!loading"><div class="space-y-4">
    <div class="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3">
      <div class="flex items-center gap-3"><span class="h-2.5 w-2.5 rounded-full" :class="status.is_pro?'bg-emerald-500':'bg-slate-300'"></span><div><p class="text-sm font-bold text-slate-900" x-text="status.is_pro?'BetaKos Pro aktif':status.status==='berakhir'?'BetaKos Pro berakhir':'Akun gratis'"></p><p class="text-xs text-slate-500" x-text="status.is_pro?status.days_remaining+' hari tersisa':'Pilih paket untuk membuka fitur operasional.'"></p></div></div>
      <span x-show="status.is_pro" class="text-xs font-semibold text-slate-500" x-text="formatDate(status.subscription?.tanggal_berakhir)"></span>
    </div>
    <a x-show="promo.eligible" x-cloak :href="window.BASE_URL + '/pemilik/langganan/checkout?paket=pro_6_bulan'" class="flex items-center justify-between gap-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 hover:bg-emerald-100">
      <span class="flex items-start gap-3"><span class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-emerald-600 text-white"><?= masterIconSvg('gift', 'h-5 w-5') ?></span><span><strong class="block text-sm text-emerald-950">Klaim gratis 6 bulan pertama</strong><small class="mt-0.5 block text-xs text-emerald-700">Promo satu kali untuk pemilik dengan kos terverifikasi.</small></span></span><span class="shrink-0 text-sm font-bold text-emerald-700">Klaim →</span>
    </a>
    <div>
      <div class="mb-3 flex items-center justify-between gap-3"><h3 class="font-bold text-slate-900">Pilih durasi</h3><button type="button" @click="selectDuration(recommendedDuration)" class="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800" x-text="recommendedLabel"></button></div>
      <div class="grid gap-3 sm:grid-cols-3"><template x-for="item in paket" :key="item.id_paket_langganan"><button type="button" @click="selectedPackageCode=item.kode" class="relative rounded-2xl border bg-white p-4 text-left transition" :class="selectedPackageCode===item.kode?'border-emerald-500 ring-2 ring-emerald-100':'border-slate-200 hover:border-slate-300'">
        <span x-show="item.durasi_bulan===recommendedDuration" class="absolute right-3 top-3 rounded-full bg-amber-100 px-2 py-1 text-[9px] font-black text-amber-800">TERBAIK</span><span x-show="selectedPackageCode===item.kode" class="absolute bottom-3 right-3 flex h-5 w-5 items-center justify-center rounded-full bg-emerald-600 text-white"><?= masterIconSvg('check', 'h-3.5 w-3.5') ?></span>
        <p class="text-xs font-semibold text-slate-500" x-text="durationLabel(item.durasi_bulan)"></p><p class="mt-2 text-xl font-extrabold text-slate-900" x-text="formatRupiah(item.pricing?.harga_final)"></p><p class="mt-1 text-xs text-slate-500" x-text="formatRupiah(item.harga_bulanan)+'/bulan'"></p><p x-show="item.pricing?.diskon_promo" class="mt-2 text-xs font-semibold text-emerald-700" x-text="'Hemat '+formatRupiah(item.pricing?.diskon_promo)"></p>
      </button></template></div>
    </div>
    <div class="rounded-2xl border border-slate-200 bg-white p-4"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Termasuk dalam Pro</p><ul class="mt-3 grid gap-2 text-sm text-slate-700 sm:grid-cols-2 lg:grid-cols-3"><template x-for="fitur in (selectedPackage?.fitur||[])" :key="fitur"><li class="flex items-center gap-2"><span class="text-emerald-600"><?= masterIconSvg('check', 'h-4 w-4') ?></span><span x-text="fitur"></span></li></template></ul></div>
    <div class="flex flex-col gap-3 rounded-2xl bg-slate-900 p-4 text-white sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs text-slate-400" x-text="durationLabel(selectedPackage?.durasi_bulan)"></p><p class="mt-1 text-xl font-extrabold" x-text="formatRupiah(selectedPrice)"></p></div><a x-show="!pendingPayment" :href="checkoutUrl" class="btn-subscription">Lanjut ke checkout →</a><a x-show="pendingPayment" :href="window.BASE_URL + '/pemilik/langganan/pembayaran'" class="btn-subscription">Lihat pembayaran</a></div>
  </div></template>
</div>
<script>
function pemilikLanggananPage(){return{loading:true,upgradeRequested:<?= !empty($upgrade_requested)?'true':'false' ?>,status:{is_pro:false,status:'gratis',subscription:null,days_remaining:0},paket:[],promo:{eligible:false},pendingPayment:null,selectedPackageCode:'pro_1_tahun',get selectedPackage(){return this.paket.find(i=>i.kode===this.selectedPackageCode)||this.paket[0]||null},get selectedPrice(){return Number(this.selectedPackage?.pricing?.harga_final||0)},get hasFirstPromo(){return this.paket.some(i=>Number(i.pricing?.promo_bulan||0)>0)},get recommendedDuration(){return this.hasFirstPromo?12:24},get recommendedLabel(){return this.hasFirstPromo?'Terbaik: 1 Tahun':'Paling hemat: 2 Tahun'},get checkoutUrl(){return window.BASE_URL+'/pemilik/langganan/checkout?paket='+encodeURIComponent(this.selectedPackageCode)},selectDuration(m){const i=this.paket.find(i=>Number(i.durasi_bulan)===Number(m));if(i)this.selectedPackageCode=i.kode},durationLabel(m){return Number(m)===12?'1 Tahun':Number(m)===24?'2 Tahun':'6 Bulan'},async init(){try{const r=await API.get('/pemilik/langganan',false);this.status=r.data.status||this.status;this.paket=r.data.paket||[];this.promo=r.data.promo||this.promo;this.pendingPayment=r.data.pending_payment||null;const p=new URLSearchParams(location.search).get('paket');if(p&&this.paket.some(i=>i.kode===p))this.selectedPackageCode=p;else if(!this.paket.some(i=>i.kode===this.selectedPackageCode)&&this.paket[0])this.selectedPackageCode=this.paket[0].kode}finally{this.loading=false}},formatRupiah(v){return Alpine.store('utils').formatRupiah(v)},formatDate(v){return Alpine.store('utils').formatDate(v)}}}
</script>
